modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="new_minecraft_test"
version="1.0.0"
displayName="new minecraft test"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="kirby, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.new_minecraft_test]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.new_minecraft_test]]
    modId="miapi"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


